export { TitleRelationsProcessorService } from './title-relations.processor.service'
export { PosterRelationProcessor } from './poster-relation.processor'
export { CertificateRelationProcessor } from './certificate-relation.processor'
export { CreditRelationProcessor } from './credit-relation.processor'
export { CriticReviewRelationProcessor } from './critic-review-relation.processor'
export { RatingRelationProcessor } from './rating-relation.processor'
export { GenreRelationProcessor } from './genre-relation.processor'
export { CountryRelationProcessor } from './country-relation.processor'
export { LanguageRelationProcessor } from './language-relation.processor'
// export { AvatarRelationProcessor } from './avatar-relation.processor'
// export { NameRelationProcessor } from './name-relation.processor'
